Surgery Merger
KAT-Advanced-Medical/KAM pull request #122
Opened 2022-06-06 03:31 UTC by mazinskihenry

Starting Work

2022-06-06 07:11 UTC, MiszczuZPolski requested changes
Quick review
Cope, bird boy

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayName = "Check Breath";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayName = "Perform Dialysis";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayNameProgress = "Performing";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayName = "Check Fracture";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayNameProgress = "Checking Fracture";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayName = "Perform Closed Reduction";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayNameProgress = "Performing Reduction";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayName = "Perform Open Reduction";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayNameProgress = "Performing Reduction";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayName = "Push Etomidate";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayName = "Push Lorazepam";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayName = "Push Flumazenil";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayName = "Expose fracture";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayNameProgress = "Exposing";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayName = "Peform Incision";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayNameProgress = "Performing Incision";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayName = "Clamp Fracture";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayNameProgress = "Clamping Fracture";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayName = "Irrigate Wound";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayNameProgress = "Irrigating";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayName = "Debride Wounds";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayNameProgress = "Debriding";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        treatmentTime = 15;
make it settable

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayName = "Apply NPWT Dressing";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        displayNameProgress = "Applying";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        allowSelfTreatment = 8;
8? it should be 0/1

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        treatmentTime = 8;
make it settable

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/CfgWeapons.hpp
> +        displayName = "Etomidate";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/CfgWeapons.hpp
> +        displayName = "Lorazepam";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/CfgWeapons.hpp
> +        displayName = "Flumazenil";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/CfgWeapons.hpp
> +        displayName = "Scalpel";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/CfgWeapons.hpp
> +        displayName = "Retractor";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/CfgWeapons.hpp
> +        displayName = "Clamp";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/CfgWeapons.hpp
> +        displayName = "Bone Plate";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/CfgWeapons.hpp
> +        displayName = "Dressing Vacuum";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/XEH_preInit.sqf
> +#define CBA_SETTINGS_CAT_M "KAT Medical - Surgery"
"KAT - ADV Medical: Surgery"

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/functions/fnc_fractureSelectLocal.sqf
> +        _fractureString = "Compound Fracture";
CSTRING?

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/functions/fnc_fractureSelectLocal.sqf
> +        _fractureString = "Comminuted Fracture";
CSTRING?

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/functions/fnc_fractureSelectLocal.sqf
> +    _fractureString = "Simple Fracture";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/functions/fnc_fractureSelectLocal.sqf
> +        _fractureString = "Compound Fracture";
CSTRING?

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/functions/fnc_fractureSelectLocal.sqf
> +        _fractureString = "Simple Fracture";
CSTRING?

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/functions/fnc_fractureSelectLocal.sqf
> +        _fractureString = "Comminuted Fracture";
CSTRING?

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/functions/fnc_openFractureProgressLocal.sqf
> +    private _output = localize LSTRING(fracture_fail);
LLSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/functions/fnc_openFractureProgressLocal.sqf
> +        _surgeryString = "exposed";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/functions/fnc_openFractureProgressLocal.sqf
> +        _surgeryString = "irrigated";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/functions/fnc_openFractureProgressLocal.sqf
> +        _surgeryString = "clamped";
CSTRING

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/script_component.hpp
> +#include "\x\aceP\addons\main\script_mod.hpp"
aceP?

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/script_component.hpp
> +#include "\x\aceP\addons\main\script_macros.hpp"
aceP?

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        treatmentTime = 2;
make it settable

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        treatmentTime = 15;
make it settable

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        medicRequired = 1;
make it settable

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        treatmentTime = 5;
make it settable

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        medicRequired = 1;
make it settable

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        medicRequired = 1;
make it settable

2022-06-06 07:11 UTC, MiszczuZPolski commented on addons/surgery/ACE_Medical_Treatment_Actions.hpp
> +        medicRequired = 1;
make it settable

2022-06-06 09:53 UTC, YetheSamartaka commented
100% agree with Miszczu.

2022-07-06 23:55 UTC, MiszczuZPolski requested changes

2022-07-06 23:55 UTC, MiszczuZPolski commented on addons/surgery/functions/fnc_openFractureProgressLocal.sqf
> +private _output = localize LSTRING(fracture_fail);
LLSTRING

2022-07-06 23:55 UTC, MiszczuZPolski commented on addons/surgery/functions/fnc_openFractureProgressLocal.sqf
> +    private _output = localize LSTRING(fracture_fail);
LLSTRING

2022-09-11 13:13 UTC, Tomcat-SG requested changes
Need to update the missing and wrong things. Pls also check the DEV Discord Channel @Devs

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/ACE_Medical_Treatment_Actions.hpp
> +        displayName = CSTRING(Take_EACA);
string is missing in stringtable

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/ACE_Medical_Treatment_Actions.hpp
> +        displayName = "Saline Flush";
CSTRING

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/ACE_Medical_Treatment_Actions.hpp
> +        displayName = "Inspect Catheter";
CSTRING

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/ACE_Medical_Treatment_Actions.hpp
> +        displayName = "Check Breath";
CSTRING

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/CfgWeapons.hpp
> +        displayName = "EACA";
CSTRING

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/CfgWeapons.hpp
> +        descriptionShort = CSTRING(EACA_DescShort);
string is missing in stringtable

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/CfgWeapons.hpp
> +        descriptionUse = CSTRING(EACA_DescUse);
string is missing in stringtable

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/XEH_preInit.sqf
> +	["Enable Advanced Medical for AI", "Enables kidney actions and blood pressure PFHs for AI"],
LLSTRING

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/functions/fnc_alphaAction.sqf
> + * [player] call ace_medical_status_fnc_getBloodLoss
not correct

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/functions/fnc_alphaAction.sqf
> + * Total blood loss of unit (litres/second) <NUMBER>
not correct

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/functions/fnc_alphaAction.sqf
> + * 0: The Unit <OBJECT>
not correct

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/functions/fnc_alphaAction.sqf
> + * Calculate the total blood loss of a unit.
not correct

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/functions/fnc_inspectCatheter.sqf
> + * Arguments:
arguments not correct

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/functions/fnc_inspectCatheter.sqf
> + * Opens an IV/IO on a patient and changes the patient's flow variable
description not correct

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/functions/fnc_inspectCatheter.sqf
> + * [player, cursorObject, "LeftLeg", "", objNull, "kat_IV_20"] call kat_circulation_fnc_fractureCheck;
example not correct

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/functions/fnc_salineCheck.sqf
> + * Opens an IV/IO on a patient and changes the patient's flow variable
description not correct

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/functions/fnc_salineCheck.sqf
> + * Arguments:
arguments not correct

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/functions/fnc_salineCheck.sqf
> + * None
Return Value not correct

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/functions/fnc_salineCheck.sqf
> + * [player, cursorObject, "LeftLeg"] call kat_circulation_fnc_applyIV;
Example not correct

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/functions/fnc_treatmentAdvanced_EACA.sqf
> + * Airway Management for occluding
description not correct

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/functions/fnc_treatmentAdvanced_EACA.sqf
> + * [player, cursorTarget] call kat_airway_fnc_treatmentAdvanced_accuvac;
example not correct

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/functions/fnc_treatmentAdvanced_EACA.sqf
> +    ["treatmentEACA", [_patient, "EACA", _medic]] call CBA_fnc_localEvent;
eventhandler is missing in the XEH_postInit!

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/functions/fnc_treatmentAdvanced_EACALocal.sqf
> + * Begins TXA bandaging process
description not correct

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/functions/fnc_treatmentAdvanced_EACALocal.sqf
> + * 0: Medic <OBJECT>
arguments not correct

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/functions/fnc_treatmentAdvanced_EACALocal.sqf
> + * None
Return Value not correct

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/functions/fnc_treatmentAdvanced_EACALocal.sqf
> + * [player, "TXA"] call aceP_circulation_fnc_treatmentAdvanced_TXALocal;
Example not correct

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/pharma/functions/fnc_vehicleCheckDialysis.sqf
> + * None
Return Value not correct

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/surgery/XEH_postInit.sqf
> +["treatmentLido", {_this call FUNC(treatmentAdvanced_LidoLocal)}] call CBA_fnc_addEventHandler;
where do they get called?

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/surgery/functions/fnc_closedFractureLocal.sqf
> + * Arguments:
param entry is missing

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/surgery/functions/fnc_debridementClearLocal.sqf
> + * [player, cursorObject, "LeftLeg"] call kat_surgery_fnc_debridementCheckLocal;
```suggestion
 * [player, cursorObject, "LeftLeg"] call kat_surgery_fnc_debridementClearLocal;
```

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/surgery/functions/fnc_openFractureProgress.sqf
> + * [player, cursorObject, "LeftLeg"] call kat_surgery_fnc_openFractureProgress
is param 3 optional?

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/surgery/functions/fnc_init.sqf
> + * [player] call kat_circulation_fnc_init;
not correct example

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/surgery/functions/fnc_fractureCheck.sqf
> + * 2: Body Part <STRING>
param 3 is missing

2022-09-11 13:13 UTC, Tomcat-SG commented on addons/surgery/functions/fnc_openFractureCheck.sqf
> + * None
missing return value

2022-09-22 19:11 UTC, YetheSamartaka commented on addons/pharma/functions/fnc_alphaAction.sqf
> + * Calculate the total blood loss of a unit.
@MiszczuZPolski will resolve it in his Pharmacy refactor.

2022-09-22 19:13 UTC, merged