Surgery - Add Additional Settings to Allow Patient to Remain Awake During Surgeries
KAT-Advanced-Medical/KAM pull request #371
Opened 2023-07-12 06:08 UTC by Belhun

**When merged this pull request will:**

- Added 1 Dropdown Setting with 4 options In the Surgery category.(In XEH_preInit)
  - Option 1 Surgery Causes Unconsciousness: An incision causes cardiac arrest if the patient is not unconscious and sedated(With Etomidate). Uses a Switch Statement in fnc_incisionLocal.sqf 
    - Checks if the patient Has Etomidate and if they are in an unconscious state. 
  - Option 2 Unconsciousness Required for Surgery: Surgery can only begin if the patient is unconscious and sedated(With Etomidate).
    - Changed the First if statement in fnc_incisionLocal from checking for uncon_requieredForAction to Checking for unconSurgery_requieredForAction equals 1. This statement checks to make sure the patient is unconscious and if they aren't then Surgery is aborted(This setting is the old uncon_requieredForAction, Which has been brought into the switch state due to the similarity of the job)
    - Removed Setting "uncon_requieredForAction" and the localizations for the same setting 
  - Option 3 No Unconsciousness from Surgery: The patient is able to stay awake through the entirety of the surgery, experiencing a little pain and a slight increase in heart rate (Etomidate not required). Uses a Switch Statement in fnc_incisionLocal.sqf 
    - This Case Uses the adjustPainLevel and addMedicationAdjustment, to cause pain and increase in heart rate[There is a chance this can be simplified with just the addMedicationAdjustment, but was unsure when searching for similar use cases in Code so went with 2 separate functions]
  - Option 4 Surgery Anesthesia: The patient can remain awake for the duration of the surgery. However, if Etomidate hasn't been applied, the patient will lose consciousness and go into CA. There are two cases in the switch statement in fnc_incisionLocal.sqf. 
    - The first case checks the unconSurgery_requieredForAction setting and whether there's no Etomidate in the patient's system. If so, it induces cardiac arrest by causing a heart rate increase of 200 and forces the patient into unconsciousness. 
    - The second case applies when there's Etomidate in the patient's system. In this scenario, the incision can proceed without complications, allowing the surgery to be carried out without issues.
    
- Added English Translations For All Text Used in Pull Request

### IMPORTANT

- [x] [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- [x] Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2023-07-12 15:21 UTC, BlueTheKing requested changes

2023-07-12 15:21 UTC, BlueTheKing commented on addons/surgery/XEH_preInit.sqf
> +    LLSTRING(unconSurgery_requieredForAction),
Add description to explain each of the settings

2023-07-12 15:21 UTC, BlueTheKing commented on addons/surgery/functions/fnc_incisionLocal.sqf
>      if !(IS_UNCONSCIOUS(_patient)) exitWith {
Put them in one line
```suggestion
if (GVAR(unconSurgery_requieredForAction) == 1 && !(IS_UNCONSCIOUS(_patient))) exitWith {
```

2023-07-12 15:21 UTC, BlueTheKing commented on addons/surgery/functions/fnc_incisionLocal.sqf
>      };
No need for switch statement
```suggestion
    if ((GVAR(unconSurgery_requieredForAction) == 0 && !(IS_UNCONSCIOUS(_patient)) && _count == 0) || (GVAR(unconSurgery_requieredForAction) == 3 && _count == 0)) exitWith {
        [_patient, "Pain", 10, 40, 200, 0, 40] call ACEFUNC(medical_status,addMedicationAdjustment);
        [_target, true] call ACEFUNC(medical,setUnconscious);
    };

    if (GVAR(unconSurgery_requieredForAction) == 2 && _count == 0) then {
        [_patient, 0.4] call ACEFUNC(medical_status,adjustPainLevel);
        [_patient, "Pain", 10, 40, 30, 0, 40] call ACEFUNC(medical_status,addMedicationAdjustment);
    };
```

2023-07-12 15:21 UTC, BlueTheKing commented on addons/surgery/stringtable.xml
> +        </Key>
Remove extra closing tag
```suggestion
```

2023-07-12 15:21 UTC, BlueTheKing commented on addons/surgery/functions/fnc_openReductionProgressLocal.sqf
>      if !(IS_UNCONSCIOUS(_patient)) exitWith {
```suggestion
if (GVAR(unconSurgery_requieredForAction) == 1 && !(IS_UNCONSCIOUS(_patient))) exitWith {
```

2023-07-12 23:16 UTC, Belhun commented on addons/surgery/functions/fnc_incisionLocal.sqf
>      };
That makes a lot more sense. Though, would it make more sense to check if the Etomidate count is zero before checking if the other states are true? I'm new to this, to be honest, so please let me know if my logic is flawed.

2023-07-12 23:49 UTC, BlueTheKing commented on addons/surgery/functions/fnc_incisionLocal.sqf
>      };
Yeah you could, don't think it'd make too much of a difference in this case.

2023-07-13 01:01 UTC, Belhun commented on addons/surgery/functions/fnc_incisionLocal.sqf
>      };
Looking back it and talking with my friend, realized that it was better with the way you suggested

2023-07-13 01:08 UTC, Belhun commented
Fixed Requested Changes and murged Spanish Translations into my Forked version

2023-07-13 07:21 UTC, Belhun commented
Oh also, on a side note, i was able to use hemtt and dev and launch it, but I couldn't Build it/release it with hemtt(it said it is a hemtt issue, an not something i did but still thought Id say something )

2023-07-13 11:28 UTC, BlueTheKing approved these changes
Builds, tested, looks good.

2023-07-13 11:58 UTC, MiszczuZPolski approved these changes

2023-07-13 20:55 UTC, merged