Pharma - Change, Limiting non-Opioid Relief
KAT-Advanced-Medical/KAM pull request #460
Opened 2023-12-31 08:35 UTC by mazinskihenry

**When merged this pull request will:**
- Create a maxRelief variable for medications to create hard ceilings for pain reduction
- Apply this ceiling to Painkillers and Penthrox 

### IMPORTANT

- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2024-01-05 08:20 UTC, MiszczuZPolski requested changes
Whats default value of opioid relief because in handleRespawn/init its 1 but in getVariable you used 0 as default value.
I would like to add more stuff about changes to your PR description so it can be undestood better

2024-01-05 08:20 UTC, MiszczuZPolski commented on addons/pharma/functions/fnc_treatmentAdvanced_FentanylLocal.sqf
> +private _opioidFactor = _target getVariable (QGVAR(opioidFactor), 0);
```suggestion
private _opioidFactor = _target getVariable [QGVAR(opioidFactor), 0];
```

2024-01-05 08:20 UTC, MiszczuZPolski commented on addons/pharma/functions/fnc_treatmentAdvanced_FentanylLocal.sqf
> +    _target setVariable (QGVAR(opioidFactor), _opioidRelief, true);
```suggestion
    _target setVariable [QGVAR(opioidFactor), _opioidRelief, true];
```

2024-01-05 08:20 UTC, MiszczuZPolski commented on addons/pharma/functions/fnc_treatmentAdvanced_MorphineLocal.sqf
> +private _opioidFactor = _patient getVariable (QGVAR(opioidFactor), 0);
```suggestion
private _opioidFactor = _patient getVariable [QGVAR(opioidFactor), 0];
```

2024-01-05 08:20 UTC, MiszczuZPolski commented on addons/pharma/functions/fnc_treatmentAdvanced_MorphineLocal.sqf
> +    _patient setVariable (QGVAR(opioidFactor), _opioidRelief, true);
```suggestion
    _patient setVariable [QGVAR(opioidFactor), _opioidRelief, true];
```

2024-01-05 08:20 UTC, MiszczuZPolski commented on addons/pharma/functions/fnc_treatmentAdvanced_NalbuphineLocal.sqf
> +private _opioidFactor = _patient getVariable (QGVAR(opioidFactor), 0);
```suggestion
private _opioidFactor = _patient getVariable [QGVAR(opioidFactor), 0];
```

2024-01-05 08:20 UTC, MiszczuZPolski commented on addons/pharma/functions/fnc_treatmentAdvanced_NalbuphineLocal.sqf
> +    _patient setVariable (QGVAR(opioidFactor), _opioidRelief, true);
```suggestion
    _patient setVariable [QGVAR(opioidFactor), _opioidRelief, true];
```

2024-01-05 08:20 UTC, MiszczuZPolski commented on addons/pharma/functions/fnc_medicationLocal.sqf
> +private _adjustments = _patient getVariable [VAR_MEDICATIONS,[]];
where is it used?

2024-01-05 08:20 UTC, MiszczuZPolski commented on addons/pharma/functions/fnc_medicationLocal.sqf
> +        _painReduce = _painReduce / 4;
so if we have pain 1.0, and max Relief is only 0.6 then we will only lower it by only 0.25? looking at penthrox

2024-01-05 08:20 UTC, MiszczuZPolski commented on addons/main/script_macros.hpp
> +#define GET_DAMAGE_THRESHOLD(unit)  ((unit getVariable [QACEGVAR(medical,damageThreshold), [ACEGVAR(medical,AIDamageThreshold),ACEGVAR(medical,playerDamageThreshold)] select (isPlayer unit)]) * VAR_O
🤔 but opiod is never bigger than 1 so if i understand correctly we lower player damage threshold when we give them certain meds?

2024-02-26 22:15 UTC, MissHeda commented on addons/pharma/functions/fnc_treatmentAdvanced_FentanylLocal.sqf
> + * [player, "LeftLeg", opioidRelief] call kat_pharma_fnc_treatmentAdvanced_FentanylLocal;
change opioidRelief to number in example call

2024-02-26 22:15 UTC, MissHeda commented on addons/pharma/ACE_Medical_Treatment.hpp
> +            maxRelief = 0.6;
Why add maxRelief to medication that does not suppresses pain?

2024-02-26 22:15 UTC, MissHeda commented on addons/pharma/ACE_Medical_Treatment.hpp
> +            maxRelief = 0.6;
Why add maxRelief to medication that does not suppresses pain?

2024-02-26 22:15 UTC, MissHeda commented on addons/pharma/ACE_Medical_Treatment.hpp
> +            opioidRelief = 1.5;
Why add maxRelief to medication that does not suppresses pain?

2024-03-09 23:38 UTC, closed without merging