Tourniquet duplicity
KAT-Advanced-Medical/KAM pull request #48
Opened 2020-11-19 17:18 UTC by YetheSamartaka

- removes settable tourniquet time option since it is added by ACE

2020-11-19 17:20 UTC, Conrimaceogain commented
LGTM, let's make sure that things play happily with the ACE settings and then we should be good to merge.

2020-11-19 17:21 UTC, YetheSamartaka commented
Indeed

2020-11-19 17:24 UTC, Conrimaceogain approved these changes

2020-11-23 21:12 UTC, Tomcat-SG requested changes
Pls fix these things. Im not sure if the % on the turkish translation could cause at this position an error, because it is followed by a number, but it is better in this way, so it cant cause any errors

2020-11-23 21:12 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <Turkish>Nabız Oksimetresi: HR:%1 Sp02:%2</Turkish>
```suggestion
            <Turkish>Nabız Oksimetresi: HR: %1 Sp02: %2</Turkish>
```

2020-11-23 21:12 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +				%1Sp02% 70'in üzerinde -> Evet
```suggestion
				%1Sp02 70% 'in üzerinde -> Evet
```

2020-11-23 21:12 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +				%1Sp02% 70'in üzerinde -> Evet
```suggestion
				%1Sp02 70% 'in üzerinde -> Evet
```

2020-11-23 21:12 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +				%1Sp02% 70'in altında -> Hayır -> eşek. Nefes</Turkish>
```suggestion
				%1Sp02 70% 'in altında -> Hayır -> eşek. Nefes</Turkish>
```

2020-11-23 21:29 UTC, Tomcat-SG approved these changes

2020-11-23 21:29 UTC, merged