Circulation - Add setting to apply AED pads during CPR
KAT-Advanced-Medical/KAM pull request #499
Opened 2024-03-12 21:34 UTC by apo-tle

**When merged this pull request will:**
- Create a setting to allow medics to apply AED pads while CPR is being performed. Not tested in multiplayer but it's a simple PR, should work fine.

### IMPORTANT

- [x] [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- [x] Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2024-03-13 13:53 UTC, MissHeda commented on addons/circulation/XEH_preInit.sqf
> +    [false],
I'd set this to true on default. If you use a "normal" 2 pandle AED placing pads via CPR is common if you know how to do it. Doing analyze requires you to stop tho.

2024-03-14 13:18 UTC, BlueTheKing requested changes

2024-03-14 13:18 UTC, BlueTheKing commented on addons/circulation/XEH_preInit.sqf
> +//use aed during compressions - apo_tle
```suggestion
// Allow application of AED pads while CPR is performed
```

2024-03-14 13:18 UTC, BlueTheKing commented on addons/circulation/functions/fnc_Defibrillator_Pads_CheckCondition.sqf
> +_condition && !(_patient getVariable [QGVAR(DefibrillatorPads_Connected), false]) && !(_patient getVariable [QEGVAR(airway,recovery), false]) && (objectParent _patient isEqualTo objectParent _medic)
```suggestion
_condition && !(_patient getVariable [QGVAR(DefibrillatorPads_Connected), false]) && !(_patient getVariable [QEGVAR(airway,recovery), false]) && (objectParent _patient isEqualTo objectParent _medic) && (["",_patient] call ACEFUNC(medical_treatment,canCPR) || GVAR(AED_duringCpr));
```

2024-03-14 18:04 UTC, BlueTheKing approved these changes

2024-03-20 19:55 UTC, MissHeda approved these changes

2024-03-25 14:20 UTC, merged