Pharmacy - Change the IO painkiller checks
KAT-Advanced-Medical/KAM pull request #501
Opened 2024-03-19 18:10 UTC by Cplhardcore

**When merged this pull request will:**
- _Change the pain addition with an IO to only apply when a medication is at its strongest_
- _Add the missing pain meds (Fentanyl/Ketamine/Nalbuphine) to the check_

### IMPORTANT

- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2024-03-19 19:38 UTC, BlueTheKing requested changes

2024-03-19 19:38 UTC, BlueTheKing commented on addons/pharma/functions/fnc_applyIV.sqf
> +    if (_count <=  0.6 && _count2 <=  0.6 && _count3 <=  0.6 && _count4 <=  0.6 && _count5 <=  0.6) then {[_patient, 0.8] call ACEFUNC(medical_status,adjustPainLevel)};
```suggestion
    private _lidocaineCount = [_patient, "Lidocaine", false] call ACEFUNC(medical_status,getMedicationCount);
    private _morphineCount = [_patient, "Morphine", false] call ACEFUNC(medical_status,getMedicationCount);
    private _nalbuphineCount = [_patient, "Nalbuphine", false] call ACEFUNC(medical_status,getMedicationCount);
    private _fentanylCount = [_patient, "Fentanyl", false] call ACEFUNC(medical_status,getMedicationCount);
    private _ketamineCount = [_patient, "Ketamine", false] call ACEFUNC(medical_status,getMedicationCount);
    if (_lidocaineCount <= 0.6 && _morphineCount <= 0.6 && _nalbuphineCount <= 0.6 && _fentanylCount <= 0.6 && _ketamineCount <= 0.6) then {[_patient, 0.8] call ACEFUNC(medical_status,adjustPainLevel)};
```

2024-03-19 19:38 UTC, BlueTheKing commented on addons/surgery/functions/fnc_closedReductionLocal.sqf
> +if (_count <=  0.8 && _count2 <=  0.8 && _count3 <=  0.8 && _count4 <=  0.8 && _count5 <=  0.8) then {
```suggestion
private _lidocaineCount = [_patient, "Lidocaine", false] call ACEFUNC(medical_status,getMedicationCount);
private _morphineCount = [_patient, "Morphine", false] call ACEFUNC(medical_status,getMedicationCount);
private _nalbuphineCount = [_patient, "Nalbuphine", false] call ACEFUNC(medical_status,getMedicationCount);
private _fentanylCount = [_patient, "Fentanyl", false] call ACEFUNC(medical_status,getMedicationCount);
private _ketamineCount = [_patient, "Ketamine", false] call ACEFUNC(medical_status,getMedicationCount);
if (_lidocaineCount <= 0.8 && _morphineCount <= 0.8 && _nalbuphineCount <= 0.8 && _fentanylCount <= 0.8 && _ketamineCount <= 0.8) then {
```

2024-03-19 19:47 UTC, Cplhardcore commented on addons/pharma/functions/fnc_applyIV.sqf
> +    if (_count <=  0.6 && _count2 <=  0.6 && _count3 <=  0.6 && _count4 <=  0.6 && _count5 <=  0.6) then {[_patient, 0.8] call ACEFUNC(medical_status,adjustPainLevel)};
Fixed

2024-03-19 19:47 UTC, Cplhardcore commented on addons/surgery/functions/fnc_closedReductionLocal.sqf
> +if (_count <=  0.8 && _count2 <=  0.8 && _count3 <=  0.8 && _count4 <=  0.8 && _count5 <=  0.8) then {
Fixed

2024-03-19 20:23 UTC, BlueTheKing approved these changes

2024-03-25 14:13 UTC, MiszczuZPolski approved these changes

2024-03-25 14:14 UTC, merged