Spanish translation of the new elements
KAT-Advanced-Medical/KAM pull request #516
Opened 2024-04-09 14:30 UTC by Ruben0705

- Spanish translation of the new elements

With the new update, several elements have been added and others have been modified, here are the ones I have been able to find to translate them.

2024-04-15 15:29 UTC, Gilfor requested changes
En misc de la 1244 a la 1255 borras líneas, ponlas de nuevo

Buen curro, gracias.

2024-04-15 15:29 UTC, Gilfor commented on addons/airway/stringtable.xml
> +            <Spanish>La bomba de succión manual es un dispositivo de succión médico para la succión manual de las vías respiratorias. Esta alternativa a los dispositivos eléctricos.</Spanish>
```suggestion
            <Spanish>La bomba de succión manual es un dispositivo de succión médico para la succión manual de las vías respiratorias. Es alternativa a los dispositivos eléctricos.</Spanish>
```

2024-04-15 15:29 UTC, Gilfor commented on addons/breathing/stringtable.xml
> +            <Spanish>Establece si la simulación de SPO2 y según la funcionalidad como Neumotórax y \nVía aérea: oclusión &amp; La obstrucción (se desactivará la reducción de SPO2) debe estar activada
```suggestion
            <Spanish>Establece si la simulación de SPO2 y las funcionalidades del mismo como Neumotórax y \nvías respiratorias: oclusión/obstrucción (se desactivará la reducción de SPO2). deberían estar activadas</Spanish>
```

2024-04-15 15:29 UTC, Gilfor commented on addons/misc/stringtable.xml
> +            <Spanish>Desenpaquetar sección de miscelaneos:</Spanish>
```suggestion
            <Spanish>Desempaquetar sección de traumas:</Spanish>
```

2024-04-15 15:29 UTC, Gilfor commented on addons/misc/stringtable.xml
> +            <Spanish>Desenpaquetar sección de trauma:</Spanish>
```suggestion
            <Spanish>Empaquetar sección de trauma:</Spanish>
```

2024-04-15 15:29 UTC, Gilfor commented on addons/misc/stringtable.xml
> +            <Spanish>Desenpaquetar sección de miscelaneos:</Spanish>
```suggestion
            <Spanish>Desempaquetar sección de miscelaneos:</Spanish>
```

2024-04-15 15:29 UTC, Gilfor commented on addons/misc/stringtable.xml
> +            <Spanish>Desenpaquetar sección de fluidos:</Spanish>
```suggestion
            <Spanish>Desempaquetar sección de fluidos:</Spanish>
```

2024-04-15 15:29 UTC, Gilfor commented on addons/misc/stringtable.xml
> +            <Spanish>Desenpaquetar sección de farmacia:</Spanish>
```suggestion
            <Spanish>Desempaquetar sección de farmacia:</Spanish>
```

2024-04-15 15:29 UTC, Gilfor commented on addons/misc/stringtable.xml
> +            <Spanish>Desenpaquetar sección de vías respiratorias:</Spanish>
```suggestion
            <Spanish>Desempaquetar sección de vías respiratorias:</Spanish>
```

2024-04-15 15:29 UTC, Gilfor commented on addons/misc/stringtable.xml
> +            <Spanish>Desenpaquetar sección de respiración:</Spanish>
```suggestion
            <Spanish>Desempaquetar sección de respiración:</Spanish>
```

2024-04-15 15:29 UTC, Gilfor commented on addons/misc/stringtable.xml
> +            <Spanish>Desenpaquetar sección de analgesicos:</Spanish>
```suggestion
            <Spanish>Desempaquetar sección de analgesicos:</Spanish>
```

2024-04-15 15:29 UTC, Gilfor commented on addons/misc/stringtable.xml
> +            <Spanish>Desenpaquetar sección de vendaje:</Spanish>
```suggestion
            <Spanish>Desempaquetar sección de vendaje:</Spanish>
```

2024-04-15 15:29 UTC, Gilfor commented on addons/misc/stringtable.xml
> +            <Spanish>Nota color del elemento</Spanish>
```suggestion
            <Spanish>Color del objeto en la nota</Spanish>
```

2024-04-15 15:29 UTC, Gilfor commented on addons/misc/stringtable.xml
> +            <Spanish>El color del elemento del texto que se muestra mediante una nota.</Spanish>
```suggestion
            <Spanish>El color del elemento que aparece en el texto de la nota.</Spanish>
```

2024-04-15 15:29 UTC, Gilfor commented on addons/misc/stringtable.xml
> +            <Spanish>Seccióm de color del la nota</Spanish>
```suggestion
            <Spanish>Sección de color de la nota</Spanish>
```

2024-04-15 15:29 UTC, Gilfor commented on addons/misc/stringtable.xml
> +            <Spanish>Utilice kit quirúrgico (cuerpo completo)</Spanish>
```suggestion
            <Spanish>Utilizar kit quirúrgico (cuerpo completo)</Spanish>
```

2024-04-18 22:50 UTC, Gilfor commented
En misc de la 1244 a la 1255 borras líneas, ponlas de nuevo

Tienes que hacer esto para que te lo hagan merge.

2024-04-19 09:20 UTC, Ruben0705 commented
Lo estoy intentando pero puede ser que tenga que borrar la branch porque no me deja hacer el commit y tampoco puedo hacerle un pull de lo que te comitee, me dice que es invalido porque esta branch no esta mergeada.

2024-06-03 14:30 UTC, Gilfor commented
He estado muy liado, cualquier cosa háblame por DC a Gilfor#4767

2024-07-20 20:07 UTC, closed without merging