Pharma - Add TXA autoinjector
KAT-Advanced-Medical/KAM pull request #534
Opened 2024-05-15 18:02 UTC by Cplhardcore

**When merged this pull request will:**
- Add a TXA autoinjector to KAM, applies unstable clots if coag is disabled

### IMPORTANT

- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2024-06-07 23:54 UTC, simulified commented
There is a problem
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 1000; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

2024-06-09 01:37 UTC, MiszczuZPolski requested changes
small review but if this ever gets merged :kappa: it would be done after #545

2024-06-09 01:37 UTC, MiszczuZPolski commented on addons/pharma/ACE_Medical_Treatment_Actions.hpp
> +        allowedSelections[] = {"LeftArm", "RightArm", "LeftLeg", "RightLeg"};
no need for that

2024-06-09 01:37 UTC, MiszczuZPolski commented on addons/pharma/ACE_Medical_Treatment_Actions.hpp
> +        allowSelfTreatment = 1;
no need for that

2024-06-09 01:37 UTC, MiszczuZPolski commented on addons/pharma/ACE_Medical_Treatment_Actions.hpp
> +        condition = "";
no need for that

2024-06-09 01:37 UTC, MiszczuZPolski commented on addons/pharma/ACE_Medical_Treatment_Actions.hpp
> +        sounds[] = {};
we can use morphine injection for this sound so if you are okay with that, just delete this entry too

2024-06-09 01:37 UTC, MiszczuZPolski commented on addons/pharma/XEH_postInit.sqf
> +[QGVAR(txaautoLocal), LINKFUNC(treatmentAdvanced_TXAAutoLocal)] call CBA_fnc_addEventHandler;
```suggestion
[QGVAR(TXAAutoLocal), LINKFUNC(treatmentAdvanced_TXAAutoLocal)] call CBA_fnc_addEventHandler;
```

2024-06-14 18:01 UTC, mazinskihenry commented
At this current time we are going to close this PR. When RX Bandz finishes their TXA autoinjector, we can come back to this, but currently there is no TXA formulation that can be used in an autoinjector, and we would like to keep it constrained as an IV medication because of how powerful it is.

2024-06-14 18:01 UTC, closed without merging