Fixed chemical zeus module (DW polski I change the title + description once I calm down)
KAT-Advanced-Medical/KAM pull request #551
Opened 2024-06-15 13:56 UTC by AtrixZockt

I hate this bs...

**When merged this pull request will:**
- _Describe what this pull request will do_
- _Each change in a separate line_

### IMPORTANT

- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2024-06-15 14:22 UTC, YetheSamartaka requested changes
Please remove systemChat messages.

2024-06-15 14:22 UTC, YetheSamartaka commented on addons/chemical/functions/fnc_gasCheck.sqf
> +systemChat "Gas check started";
left systemChat from debugging

2024-06-15 14:22 UTC, YetheSamartaka commented on addons/chemical/functions/fnc_gasCheck.sqf
> +systemChat str _logic;
here as well

2024-06-15 14:22 UTC, YetheSamartaka commented on addons/chemical/functions/fnc_gasCheck.sqf
> +                systemChat format["Player treated: %1", _x];
systemChat

2024-06-15 14:22 UTC, YetheSamartaka commented on addons/chemical/functions/fnc_gasCheck.sqf
> +                systemChat format["Player in Zone: %1", _x];
systemChat

2024-06-15 14:22 UTC, YetheSamartaka commented on addons/chemical/functions/fnc_gasCheck.sqf
> +                    systemChat format["Player left Zone: %1", _x];
systemChat

2024-06-15 14:22 UTC, YetheSamartaka commented on addons/chemical/functions/fnc_gasCheckLocal.sqf
> +systemChat "Local Gas Check started";
systemChat

2024-06-15 14:22 UTC, YetheSamartaka commented on addons/chemical/functions/fnc_ui_gasModule.sqf
> +systemChat "Initialize Module Test";
systemChat

2024-06-15 14:22 UTC, YetheSamartaka commented on addons/chemical/functions/fnc_ui_gasModule.sqf
> +systemChat str _ctrlButtonOK;
systemChat

2024-06-15 14:22 UTC, YetheSamartaka commented on addons/chemical/functions/fnc_ui_gasModule.sqf
> +    systemChat "Module Confirm Click";
systemChat

2024-06-15 14:22 UTC, YetheSamartaka commented on addons/chemical/functions/fnc_ui_gasModule.sqf
> +            systemChat "Module Gas Check Initialize";
systemChat

2024-06-15 14:22 UTC, YetheSamartaka commented on addons/chemical/functions/fnc_ui_gasModule.sqf
> +            systemChat "Module Gas Check Initialize";
systemChat

2024-06-16 17:04 UTC, YetheSamartaka approved these changes

2024-07-24 17:37 UTC, MiszczuZPolski approved these changes

2024-07-24 17:37 UTC, merged