Translations - Add Spanish
KAT-Advanced-Medical/KAM pull request #572
Opened 2024-08-01 20:24 UTC by TNameLess

**When merged this pull request will:**
- Add remaining Spanish translation in Breathing, Circulation & Pharma

2024-08-02 08:10 UTC, MiszczuZPolski commented
Fix your stringtables, you messed up all of them
![image](https://github.com/user-attachments/assets/8e11e838-b742-42e2-bf66-d791b333470f)
![image](https://github.com/user-attachments/assets/1c5f1e0d-0d88-4431-8edf-680dcdc2d821)

2024-08-08 09:35 UTC, Gilfor requested changes
Te paso algunas correcciones que me han pedido hacer, cualquier cosa me tienes por el DC: Gilfor#4767

2024-08-08 09:35 UTC, Gilfor commented on addons/pharma/stringtable.xml
> +            <Spanish>Usar CWMP</Spanish>
Sigue mejor la linea del portugués, porque las siglas no las mencionamos antes y en castellano no encontré nada.

```suggestion
            <Spanish>Usar Comprimidos de Combate</Spanish>
```

2024-08-08 09:35 UTC, Gilfor commented on addons/pharma/stringtable.xml
> +            <Spanish>Si el ATX esta permitido, se podrá apilar y duplicará su eficiencia</Spanish>
```suggestion
            <Spanish>Si el ATX esta permitido, se podrá acumular y duplicará su eficiencia</Spanish>
```

2024-08-08 09:35 UTC, Gilfor commented on addons/pharma/stringtable.xml
> +            <Spanish>Permitir apilado</Spanish>
```suggestion
            <Spanish>Permitir acumulación</Spanish>
```

2024-08-08 09:35 UTC, Gilfor commented on addons/pharma/stringtable.xml
> +            <Spanish>Requiere Volumen de Sangre</Spanish>
```suggestion
            <Spanish>Volumen de sangre requerido</Spanish>
```

2024-08-08 09:35 UTC, Gilfor commented on addons/pharma/stringtable.xml
> +            <Spanish>Minimo volumen de sangre necesario para que la coagulación funcione</Spanish>
```suggestion
            <Spanish>Volumen de sangre necesario para que la coagulación funcione</Spanish>
```

2024-08-08 09:35 UTC, Gilfor commented on addons/pharma/stringtable.xml
> +            <Spanish>Ciclo de tiempo de la coagulación</Spanish>
```suggestion
            <Spanish>Duración del ciclo de coagulación</Spanish>
```

2024-08-08 09:35 UTC, Gilfor commented on addons/pharma/stringtable.xml
> +            <Spanish>El tiempo entre cada ciclo de coagulación de la herida que inicia la coagulación de la herida. (Un número bajo puede causar lag)</Spanish>
```suggestion
            <Spanish>El tiempo entre cada ciclo de coagulación de la herida que inicia la coagulación. (Un número bajo puede causar lag)</Spanish>
```

2024-08-08 09:35 UTC, Gilfor commented on addons/pharma/stringtable.xml
> +            <Spanish>Tiempo que transcurre entre cada revisión de la regeneración del factor de coagulación. Añade +1 factor si la revisión ha tenido exito. Utiliza el ajuste "Factores de Coagulación
```suggestion
            <Spanish>Tiempo que transcurre entre cada revisión de la regeneración del factor de coagulación. Añade +1 factor si la revisión ha tenido exito. Utiliza el ajuste "Factores de Coagulación" como límite.\n Nota: Si el limite es excedido, el tiempo será usado para retirar -1 factor hasta que el ajuste "Factor de Coagulación" se alcance. Consejo: ATX o EACA dejan de perder factores.\n Requisitos para que la regeneración funcione:\n- Ninguna herida coagulada en la última revisión del ciclo de este ajuste.\n- Ajuste: "Requiere Ritmo Cardiaco"\n- Ajuste: "Requiere Volumen de Sangre requerido " </Spanish>
```

2024-08-08 09:35 UTC, Gilfor commented on addons/pharma/stringtable.xml
> +            <Spanish>Permitir que la coaguación afecte ala unidades de IA. Todos los demás valores seguiran siendo necesario si se activa. (Puede causar lag si hay muchas IA presentes)</Spanish>
```suggestion
            <Spanish>Permitir que la coaguación afecte a las unidades de IA. Todos los demás valores seguirán siendo necesarios si se activan. (Puede causar lag si hay muchas IA presentes)</Spanish>
```

2024-08-08 09:35 UTC, Gilfor commented on addons/pharma/stringtable.xml
> +            <Spanish>Toniquete Bloquea la Coagulación de la Sangre</Spanish>
```suggestion
            <Spanish>Torniquete Bloquea la Coagulación de la Sangre</Spanish>
```

2024-08-08 09:35 UTC, Gilfor commented on addons/pharma/stringtable.xml
> +            <Spanish>Si se permite, cada parte del cuerpo se tratará simultáneamente mediante coagulación. \nEs decir, si tiene una herida en la cabeza y en el torno, ambas se tratarán en el mismo ci
```suggestion
            <Spanish>Si se permite, cada parte del cuerpo se tratará simultáneamente mediante coagulación. \nEs decir, si tiene una herida en la cabeza y otra en el torso, ambas se tratarán en el mismo ciclo de coagulación.</Spanish>
```

2024-08-08 09:35 UTC, Gilfor commented on addons/pharma/stringtable.xml
> +            <Spanish>Permitir que los Coágulos se Muestre en el Menú</Spanish>
```suggestion
            <Spanish>Permitir que los Coágulos se muestren en el Menú</Spanish>
```

2024-08-08 09:35 UTC, Gilfor commented on addons/pharma/stringtable.xml
> +            <Spanish>igeramente por debajo del INR normal</Spanish>
```suggestion
            <Spanish>ligeramente por debajo del INR normal</Spanish>
```

2024-08-08 09:35 UTC, Gilfor commented on addons/pharma/stringtable.xml
> +            <Spanish>ivel médico requerido para Coag-Sense</Spanish>
```suggestion
            <Spanish>Nivel médico requerido para Coag-Sense</Spanish>
```

2024-08-08 09:35 UTC, Gilfor commented on addons/pharma/stringtable.xml
> +            <Spanish>Permitir apilado</Spanish>
```suggestion
            <Spanish>Permitir acumulación</Spanish>
```

2024-08-08 09:35 UTC, Gilfor commented on addons/pharma/stringtable.xml
> +            <Spanish>Si el EACA esta permitido, se podrá apilar y duplicará su eficiencia</Spanish>
```suggestion
            <Spanish>Si el EACA esta permitido, se podrá acumular y duplicará su eficiencia</Spanish>
```

2024-08-08 09:35 UTC, Gilfor commented on addons/pharma/stringtable.xml
> +            <Spanish>Ciclo de tiempo de EACA</Spanish>
```suggestion
            <Spanish>Duración del Ciclo del EACA</Spanish>
```

2024-08-08 10:24 UTC, TNameLess commented on addons/pharma/stringtable.xml
> +            <Spanish>Tiempo que transcurre entre cada revisión de la regeneración del factor de coagulación. Añade +1 factor si la revisión ha tenido exito. Utiliza el ajuste "Factores de Coagulación
```suggestion
            <Spanish>Tiempo que transcurre entre cada revisión de la regeneración del factor de coagulación. Añade +1 factor si la revisión ha tenido éxito. Utiliza el ajuste "Factores de Coagulación" como límite.\n Nota: Si el limite es excedido, el tiempo será usado para retirar -1 factor hasta que el ajuste "Factor de Coagulación" se alcance. Consejo: ATX o EACA dejan de perder factores.\n Requisitos para que la regeneración funcione:\n- Ninguna herida coagulada en la última revisión del ciclo de este ajuste.\n- Ajuste: "Requiere Ritmo Cardíaco"\n- Ajuste: "Volumen de Sangre requerido" </Spanish>
```

2024-08-08 10:27 UTC, TNameLess commented
> Te paso algunas correcciones que me han pedido hacer, buen curro, cualquier cosa me tienes por el DC: Gilfor#4767

Conforme. Muchas gracias.

2024-08-08 10:28 UTC, MiszczuZPolski commented
If it’s ready to be merged, resolve merge conflicts and I will merge it

2024-08-08 10:56 UTC, Gilfor approved these changes

2024-08-08 11:06 UTC, MiszczuZPolski commented
@TNameLess please resolve merge conflicts

2024-08-08 15:54 UTC, Gilfor requested changes
dos detalles, todo lo demas ferpecto

2024-08-08 15:54 UTC, Gilfor commented on addons/pharma/stringtable.xml
> +            <Spanish>Anestésico volátil, utilizado para suprimir el dolor moderado</Spanish>
```suggestion
            <Spanish>Anestésico inhalable, utilizado para suprimir el dolor moderado</Spanish>
```

2024-08-08 15:54 UTC, Gilfor commented on addons/pharma/stringtable.xml
> +            <Spanish>Fármaco para mejorar el rendimiento, utilizado para suprimir el dolor moderador</Spanish>
```suggestion
            <Spanish>Fármaco para mejorar el rendimiento, utilizado para suprimir el dolor moderado</Spanish>
```

2024-08-08 17:01 UTC, merged