Breathing/Circulation - Adds Device Monitoring During CPR
KAT-Advanced-Medical/KAM pull request #635
Opened 2024-10-30 07:25 UTC by mazinskihenry

**When merged this pull request will:**
- Allows medics performing CPR to see AEDX and PulseOx monitoring during CPR

- [ ] Add watch monitoring

### IMPORTANT

- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2024-11-17 19:08 UTC, MiszczuZPolski requested changes

2024-11-17 19:08 UTC, MiszczuZPolski commented on addons/breathing/functions/fnc_fullHealLocal.sqf
> +_patient setVariable [QGVAR(pulseOxAttached), false, true];
fullHeal does not clear attached pulseox, you might want to move it to init.sqf

2024-11-17 19:08 UTC, MiszczuZPolski commented on addons/circulation/functions/fnc_CPRStart.sqf
> +    [LLSTRING(StopCPR), "Change Monitoring Device", ""] call ACEFUNC(interaction,showMouseHint);
stringtable

2024-11-17 19:08 UTC, MiszczuZPolski commented on addons/circulation/functions/fnc_fullHealLocal.sqf
> +_patient setVariable [QGVAR(deviceCode), 0, true];
why do we need to clear this on fullHeal? (question to both variables, i do quick review and cant check this one big function rn)

2024-11-29 23:30 UTC, mazinskihenry commented on addons/circulation/functions/fnc_fullHealLocal.sqf
> +_patient setVariable [QGVAR(deviceCode), 0, true];
Removed from fullHeal

2024-11-29 23:30 UTC, mazinskihenry commented on addons/breathing/functions/fnc_fullHealLocal.sqf
> +_patient setVariable [QGVAR(pulseOxAttached), false, true];
Remove the variable entirely, I can do the same with the pulseoximeter variable

2024-12-03 21:08 UTC, MiszczuZPolski approved these changes

2024-12-03 21:08 UTC, merged