Translation - French v2 ;)
KAT-Advanced-Medical/KAM pull request #649
Opened 2024-12-02 20:40 UTC by Alfred-Neuman

Fix space
[Old PR fix](https://github.com/KAT-Advanced-Medical/KAM/pull/640)
More translation

2024-12-03 19:02 UTC, Fanrod-Bones requested changes
Corrections on french translations

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/chemical/stringtable.xml
> +            <French>Doit être placé sur l'objet</French>
Doit être placé sur un objet

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/circulation/stringtable.xml
> +            <French>%1 échantillon de sang</French>
Echantillon sanguin de %1

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/circulation/stringtable.xml
> +            <French>%1 échantillon de sang</French>
Ou "Echantillon de sang de %1"

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/gui/stringtable.xml
> +            <French>Tête - pas de lignes</French>
ligne

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/gui/stringtable.xml
> +            <French>Poitrine - pas de lignes</French>
ligne

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/gui/stringtable.xml
> +            <French>Tête - pas de lignes</French>
+ MAJ

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/gui/stringtable.xml
> +            <French>Poitrine - pas de lignes</French>
+ MAJUSCULE

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/gui/stringtable.xml
> +            <French>Bras droit - pas de ligne</French>
Majuscule

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/gui/stringtable.xml
> +            <French>Bras gauche - pas de ligne</French>
Majuscule

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/gui/stringtable.xml
> +            <French>Jambe droite - pas de ligne</French>
Majuscule

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/gui/stringtable.xml
> +            <French>Jambe gauche - pas de ligne</French>
Majuscule

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/gui/stringtable.xml
> +            <French>Résultats de l'ABG.</French>
Un "." en trop

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/gui/stringtable.xml
> +            <French>LA</French>
BG (pour bras gauche)

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/gui/stringtable.xml
> +            <French>RA</French>
BD (pour bras droit)

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/gui/stringtable.xml
> +            <French>LL</French>
JG (pour jambe gauche)

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/gui/stringtable.xml
> +            <French>RL</French>
JD (pour jambe droite)

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/hypothermia/stringtable.xml
> +            <French>Impact de la chaleur des mains</French>
Impact du chauffe-mains

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/hypothermia/stringtable.xml
> +            <French>Multipler pour l'impact des chauffe-mains sur le gain de chaleur</French>
Multiplicateur pour l'impact des chauffe-mains sur le gain de chaleur

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/hypothermia/stringtable.xml
> +            <French>Réchauffeur de fluide Impact</French>
Impact du réchauffeur de fluide

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/hypothermia/stringtable.xml
> +            <French>Multipler pour l'impact du réchauffement des fluides sur le gain de chaleur</French>
Multiplicateur pour...

2024-12-03 19:02 UTC, Fanrod-Bones commented on addons/hypothermia/stringtable.xml
> +            <French>Utilisez des chauffe-mains.</French>
un "." en trop et "Utiliser"

2024-12-03 21:43 UTC, Alfred-Neuman commented on addons/hypothermia/stringtable.xml
> +            <French>Multipler pour l'impact du réchauffement des fluides sur le gain de chaleur</French>
Ou
Impact pour le multiplicateur du réchauffeur de liquide sur le gain de chaleur

2024-12-03 21:51 UTC, Alfred-Neuman commented
Merci pour la relecture @Fanrod-Bones
Possible coquilles restante.

2024-12-09 14:54 UTC, Fanrod-Bones approved these changes
All of this LGTM, thank you very much for all the work !!!

2024-12-09 14:58 UTC, merged