German Translation
KAT-Advanced-Medical/KAM pull request #655
Opened 2024-12-13 19:27 UTC by ZuruZockt010

**When merged this pull request will:**
- _Describe what this pull request will do_
- _Each change in a separate line_

### IMPORTANT

- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2024-12-14 13:30 UTC, OverlordZorn requested changes
Most stuff is okey, some sentences are a bit clunky, but they are difficult. A few things are completely off.

2024-12-14 13:30 UTC, OverlordZorn commented on addons/misc/stringtable.xml
> +            <German>Aktivieren Sie Ganzkörpernaht</German>
Aktiviert das Vernähen aller Wunden

2024-12-14 13:30 UTC, OverlordZorn commented on addons/misc/stringtable.xml
> +            <German>Fügt neben dem Nähen einzelner Körperteile eine Ganzkörper-Nähoption hinzu, wobei die von ACE festgelegten Einstellungen und Werte für Konsistenz verwendet werden</German>
Fügt, neben dem Vernähen der einzelnen Wunden, die Option zum Vernähen aller Wunden hinzu. Hierbei werden die relevanten ACE Einstellungen verwendet werden.

2024-12-14 13:30 UTC, OverlordZorn commented on addons/surgery/stringtable.xml
> +            <German>Bestimmt, wie lange es dauert, REBOA-Aktionen auszuführen (Setzen , Verschieben , entfernen).</German>
Definiert die Dauer der Maßnahmen von REBOA-Aktionen (Setzen, Verschieben, Entfernen)

2024-12-14 13:30 UTC, OverlordZorn commented on addons/surgery/stringtable.xml
> +            <German>Zeit, Ultraschallmaßnahmen durchzuführen</German>
Dauer von Ultraschallmaßnahmen

2024-12-14 13:30 UTC, OverlordZorn commented on addons/surgery/stringtable.xml
> +            <German>Zeit für die Perikardpunktion</German>
Dauer einer Perikardpunktion

2024-12-14 13:30 UTC, OverlordZorn commented on addons/surgery/stringtable.xml
> +            <German>Legt fest, wie lange es dauert, eine Perikardpunktion durchzuführen</German>
Legt fest, wie lange die Durchführung einer Perikardpunktion dauert

2024-12-14 13:30 UTC, OverlordZorn commented on addons/vitals/stringtable.xml
> +            <German>Aktivieren Sie AI Simple Medical</German>
Vereinfachte Simulation bei KI

2024-12-14 13:30 UTC, OverlordZorn commented on addons/watch/stringtable.xml
> +            <German>Temperaturform auswählen</German>
Maßeinheit Temperatur

2024-12-14 13:30 UTC, OverlordZorn commented on addons/watch/stringtable.xml
> +            <German>Wählt aus, welche Temperatureinheit für die Anzeige der KATMIN-Uhr verwendet wird</German>
Definiert die Maßeinheit der angezeigten Temperatur auf dem Display der KATMIN-Uhr

2024-12-14 13:30 UTC, OverlordZorn commented on addons/watch/stringtable.xml
> +            <German>Wählt aus, welche Druckeinheit für die Anzeige der KATMIN-Uhr verwendet wird</German>
Definiert die Maßeinheit des angezeigten Drucks auf dem Display der KATMIN-Uhr

2024-12-14 13:30 UTC, OverlordZorn commented on addons/watch/stringtable.xml
> +            <German>Druckform auswählen</German>
Maßeinheit Druck

2024-12-14 13:30 UTC, OverlordZorn commented on addons/watch/stringtable.xml
> +            <German>Höhenform auswählen</German>
Maßeinheit Höhe

2024-12-14 13:30 UTC, OverlordZorn commented on addons/watch/stringtable.xml
> +            <German>Wählt aus, welche Höheneinheit für die Anzeige der KATMIN-Uhr verwendet wird</German>
Definiert die Maßeinheit der angezeigten Höhe auf dem Display der KATMIN-Uhr

2024-12-14 13:30 UTC, OverlordZorn commented on addons/watch/stringtable.xml
> +            <German>Beobachten Sie mit wichtigen Überwachungsfunktionen. Garry Owen!</German>
Uhr mit Funktionen zur Vitalitätsüberwachung. Garry Owen!

2024-12-14 13:30 UTC, OverlordZorn commented on addons/watch/stringtable.xml
> +            <German>Beobachten Sie mit wichtigen Überwachungsfunktionen</German>
Uhr mit Funktionen zur Vitalitätsüberwachung

2024-12-14 13:30 UTC, OverlordZorn commented on addons/watch/stringtable.xml
> +            <German>Beobachten Sie mit wichtigen Überwachungsfunktionen. Damit andere leben können.</German>
Uhr mit Funktionen zur Vitalitätsüberwachung. Damit andere leben können!

2024-12-14 13:51 UTC, ZuruZockt010 commented
Yea your Right , some bit Clumpy :D your secondary "Rewrite" looks better

2024-12-20 09:43 UTC, MiszczuZPolski commented
Any update on this?

2024-12-20 10:23 UTC, OverlordZorn commented
Looks like Zuru doesnt know its his turn to act.

2024-12-20 11:13 UTC, OverlordZorn requested changes

2024-12-20 11:13 UTC, OverlordZorn commented on addons/chemical/stringtable.xml
> +            <German>Wird zum Nachweis toxischer KAT-Chemikalien verwendet</German>
```suggestion
            <German>zum Nachweis toxischer KAT-Chemikalien</German>
```

2024-12-20 11:13 UTC, OverlordZorn commented on addons/chemical/stringtable.xml
> +            <German>Bestimmt, wie laut die Atemgeräusche beim Tragen der Gasmaske sind</German>
```suggestion
            <German>Bestimmt die Lautstärke der Atemgeräusche während des Tragens einer Gasmaske</German>
```

2024-12-20 11:13 UTC, OverlordZorn commented on addons/chemical/stringtable.xml
> +            <German>Wahrscheinlichkeit, eine Waffe fallen zu lassen</German>
```suggestion
            <German>Chance, die Waffe unter Tränengas zu verlieren</German>
```

2024-12-20 11:13 UTC, OverlordZorn commented on addons/chemical/stringtable.xml
> +            <German>Bestimmt die Wahrscheinlichkeit, dass die Waffe fallen gelassen wird, während man unter Tränengas steht</German>
```suggestion
            <German>Bestimmt die Wahrscheinlichkeit, die Waffe zu verlieren, während man unter dem Einfluss von Tränengas steht</German>
```

2024-12-20 11:13 UTC, OverlordZorn commented on addons/circulation/stringtable.xml
> +            <German>AI Simple Medical aktiviert?</German>
```suggestion
            <German>Vereinfachte med. Simulation für KI</German>
```

2024-12-20 11:13 UTC, OverlordZorn commented on addons/misc/stringtable.xml
> +            <German>Aktivieren Sie Ganzkörpernaht</German>
```suggestion
            <German>Aktiviert das Vernähen aller Wunden</German>
```

2024-12-20 11:13 UTC, OverlordZorn commented on addons/misc/stringtable.xml
> +            <German>Fügt neben dem Nähen einzelner Körperteile eine Ganzkörper-Nähoption hinzu, wobei die von ACE festgelegten Einstellungen und Werte für Konsistenz verwendet werden</German>
```suggestion
            <German>Fügt, neben dem Vernähen der Wunden eines jeweiligen Körperteils, die Option zum Vernähen der Wunden aller Körperteile hinzu. Hierbei werden die relevanten ACE Einstellungen verwendet werden.</German>
```

2024-12-20 11:13 UTC, OverlordZorn commented on addons/surgery/stringtable.xml
> +            <German>Bestimmt, wie lange es dauert, REBOA-Aktionen auszuführen (Setzen , Verschieben , entfernen).</German>
```suggestion
            <German>Definiert die Dauer der Maßnahmen von REBOA-Aktionen (Setzen, Verschieben, Entfernen)</German>
```

2024-12-20 11:13 UTC, OverlordZorn commented on addons/surgery/stringtable.xml
> +            <German>Zeit, Ultraschallmaßnahmen durchzuführen</German>
```suggestion
            <German>Dauer von Ultraschallmaßnahmen</German>
```

2024-12-20 11:13 UTC, OverlordZorn commented on addons/surgery/stringtable.xml
> +            <German>Zeit für die Perikardpunktion</German>
```suggestion
            <German>Dauer einer Perikardpunktion</German>
```

2024-12-20 11:13 UTC, OverlordZorn commented on addons/surgery/stringtable.xml
> +            <German>Legt fest, wie lange es dauert, eine Perikardpunktion durchzuführen</German>
```suggestion
            <German>Legt fest, wie lange die Durchführung einer Perikardpunktion dauert</German>
```

2024-12-20 11:13 UTC, OverlordZorn commented on addons/vitals/stringtable.xml
> +            <German>Aktivieren Sie AI Simple Medical</German>
```suggestion
            <German>Vereinfachte med. Simulation für KI</German>
```

2024-12-20 11:13 UTC, OverlordZorn commented on addons/watch/stringtable.xml
> +            <German>Temperaturform auswählen</German>
```suggestion
            <German>Maßeinheit Temperatur</German>
```

2024-12-20 11:13 UTC, OverlordZorn commented on addons/watch/stringtable.xml
> +            <German>Wählt aus, welche Temperatureinheit für die Anzeige der KATMIN-Uhr verwendet wird</German>
```suggestion
            <German>Definiert die Maßeinheit der angezeigten Temperatur auf dem Display der KATMIN-Uhr</German>
```

2024-12-20 11:13 UTC, OverlordZorn commented on addons/watch/stringtable.xml
> +            <German>Druckform auswählen</German>
```suggestion
            <German>Maßeinheit Druck</German>
```

2024-12-20 11:13 UTC, OverlordZorn commented on addons/watch/stringtable.xml
> +            <German>Wählt aus, welche Druckeinheit für die Anzeige der KATMIN-Uhr verwendet wird</German>
```suggestion
            <German>Definiert die Maßeinheit des angezeigten Drucks auf dem Display der KATMIN-Uhr</German>
```

2024-12-20 11:13 UTC, OverlordZorn commented on addons/watch/stringtable.xml
> +            <German>Höhenform auswählen</German>
```suggestion
            <German>Maßeinheit Höhe</German>
```

2024-12-20 11:13 UTC, OverlordZorn commented on addons/watch/stringtable.xml
> +            <German>Wählt aus, welche Höheneinheit für die Anzeige der KATMIN-Uhr verwendet wird</German>
```suggestion
            <German>Definiert die Maßeinheit der angezeigten Höhe auf dem Display der KATMIN-Uhr</German>
```

2024-12-20 11:13 UTC, OverlordZorn commented on addons/watch/stringtable.xml
> +            <German>Beobachten Sie mit wichtigen Überwachungsfunktionen</German>
```suggestion
            <German>Uhr mit Funktionen zur Vitalitätsüberwachung</German>
```

2024-12-20 11:13 UTC, OverlordZorn commented on addons/watch/stringtable.xml
> +            <German>Beobachten Sie mit wichtigen Überwachungsfunktionen. Garry Owen!</German>
```suggestion
            <German>Uhr mit Funktionen zur Vitalitätsüberwachung. Garry Owen!</German>
```

2024-12-20 11:13 UTC, OverlordZorn commented on addons/watch/stringtable.xml
> +            <German>Beobachten Sie mit wichtigen Überwachungsfunktionen. Damit andere leben können.</German>
```suggestion
            <German>Uhr mit Funktionen zur Vitalitätsüberwachung. Damit andere leben können!</German>
```

2024-12-25 01:22 UTC, ItsGiantCookie commented on addons/circulation/stringtable.xml
> +            <German>Führen Sie den ABG-Test durch</German>
"Führ ein ABG-Test durch" would be a better translation

2024-12-25 01:22 UTC, ItsGiantCookie commented on addons/circulation/stringtable.xml
> +            <German>Aktivieren Sie ABG-Tests</German>
"ABG-Tests aktivieren" would be better

2024-12-25 01:25 UTC, ItsGiantCookie commented on addons/gui/stringtable.xml
> +            <German>KOPF – KEINE LINIE</German>
Is this related to IV-Lines? If so, a better translation would be "KOPF - KEIN ZUGANG", which would also apply to each following instance.

2024-12-25 01:27 UTC, ItsGiantCookie commented on addons/hypothermia/stringtable.xml
> +            <German>Überprüfen Sie die Handwärmer</German>
"Handwärmer überprüfen" would be better

2024-12-25 01:27 UTC, ItsGiantCookie commented on addons/hypothermia/stringtable.xml
> +            <German>Verwenden Sie einen Handwärmer</German>
"Handwärmer verwenden"

2024-12-25 01:29 UTC, ItsGiantCookie commented on addons/hypothermia/stringtable.xml
> +            <German>Erwärmt IV-Flüssigkeiten. Muss auf einer bereits vorhandenen Zeile platziert werden</German>
"Erwärmt IV-Flüssigkeiten. Muss auf einer bereits vorhandenen Leitung platziert werden" would be better

2024-12-25 01:30 UTC, ItsGiantCookie commented on addons/hypothermia/stringtable.xml
> +            <German>Aufführen</German>
"Aufführen" is used in a sense like acting, "Durchführen" would be better

2024-12-25 01:34 UTC, ItsGiantCookie commented on addons/misc/stringtable.xml
> +            <German>Chirurgisches Kit verwenden (Ganzkörper)</German>
Does not match terminology used in [ACE - Medical](https://github.com/acemod/ACE3/blob/master/addons/medical_treatment/stringtable.xml)

2024-12-25 01:35 UTC, ItsGiantCookie commented on addons/pharma/stringtable.xml
> +            <German>Verwenden Sie CWMP</German>
"CWMP Verwenden" would be better

2024-12-25 01:36 UTC, ItsGiantCookie commented on addons/pharma/stringtable.xml
> +            <German>Aktivieren Sie die IV/IO-Flusskontrolle</German>
"IV/IO-Flusskontrolle aktivieren" would be better

2024-12-25 01:38 UTC, ItsGiantCookie commented on addons/pharma/stringtable.xml
> +            <German>EACA behandeltTraumata</German>
missing space

2024-12-25 01:39 UTC, ItsGiantCookie commented on addons/pharma/stringtable.xml
> +            <German>Bleiben Sie so lange verbunden, bis das System außer Betrieb ist</German>
This is incorrect grammar, "So lange verbinden, bis es aus dem Kreislauf ist" could be better, still feels rough though

2024-12-25 01:44 UTC, ItsGiantCookie commented on addons/pharma/stringtable.xml
> +            <German>Koagulation auf AI-Einheiten zulassen.\nAlle anderen Werte sind weiterhin erforderlich, wenn sie aktiviert sind. (Kann zu Verzögerungen führen, wenn viele KI vorhanden sind)</Germ
"(Kann zu Lags führen, wenn viele KI vorhanden sind)" or "(Kann zu Leistungseinbrüchen führen, wenn viele KI vorhanden sind)" would be better

2024-12-25 01:46 UTC, ItsGiantCookie commented on addons/pharma/stringtable.xml
> +            <German>Lassen Sie die Gerinnung zu, um kleinere Wunden zu beeinflussen, wenn es zur Gerinnung kommt</German>
"Lässt zu, dass Koagulation kleinere Wunden bei Gerinnung beeinflusst" could be better

2024-12-25 01:48 UTC, ItsGiantCookie commented on addons/pharma/stringtable.xml
> +            <German>Coag-Sense kommt zu dem Schluss: %1</German>
"Coag-Sense kommt zu dem Ergebnis" would be better

2024-12-25 01:49 UTC, ItsGiantCookie commented on addons/pharma/stringtable.xml
> +            <German>Messen Sie PT/INR</German>
"PT/INR Messen" would be better

2024-12-25 01:51 UTC, ItsGiantCookie commented on addons/pharma/stringtable.xml
> +            <German>Für Coag-Sense ist ein medizinisches Niveau erforderlich</German>
This sentence says that a medical level is required for the coag sense, it should instead say which medical level is required.
"Erforderliches medizinisches Niveau für den Coag-Sense"

2024-12-25 01:53 UTC, ItsGiantCookie commented on addons/pharma/stringtable.xml
> +            <German>Medizinisches Niveau für intravenös verabreichtes Epinephrine erforderlich</German>
Same as with the Coag-Sense.
"Erforderliches medizinisches Niveau für die Gabe von IV-Epinephrine"

2024-12-25 01:56 UTC, ItsGiantCookie commented on addons/stretcher/stringtable.xml
> +            <German>Trage aufheben</German>
I assume this is about the winching feature of the helistretcher, which would mean "Trage einholen" could work better

2024-12-25 01:56 UTC, ItsGiantCookie commented on addons/stretcher/stringtable.xml
> +            <German>Trage Loslassen</German>
"Trage lösen" could be better, if this relates to winching

2024-12-25 01:58 UTC, ItsGiantCookie commented on addons/surgery/stringtable.xml
> +            <German>Platzieren Sie die REBOA-Einheit</German>
"REBOA-Einheit platzieren" would be better

2024-12-25 01:58 UTC, ItsGiantCookie commented on addons/surgery/stringtable.xml
> +            <German>wird Platziert</German>
lower case p

2024-12-25 01:59 UTC, ItsGiantCookie commented on addons/surgery/stringtable.xml
> +            <German>Vorgezogene REBOA-Einheit</German>
This is for pushing the REBOA up, so it should be "REBOA-Einheit vorschieben"

2024-12-25 02:00 UTC, ItsGiantCookie commented on addons/surgery/stringtable.xml
> +            <German>Vorwärts</German>
Same as the last one "Vorschieben" would be better

2024-12-25 02:00 UTC, ItsGiantCookie commented on addons/surgery/stringtable.xml
> +            <German>Entfernen Sie die REBOA-Einheit</German>
"REBOA-Einheit entfernen" would be better

2024-12-25 02:02 UTC, ItsGiantCookie commented on addons/vitals/stringtable.xml
> +            <German>Wenden Sie vereinfachte Vitalberechnungen auf die KI-Einheit an. Was zum Sparen von FPS nützlich sein kann.</German>
"Wendet vereinfachte Vitalberechnungen auf KI-Einheit an. Was für eine bessere Leistung nützlich sein kann." would be better

2024-12-25 02:03 UTC, ItsGiantCookie commented on addons/watch/stringtable.xml
> +            <German>Feet</German>
Feet is not entirely wrong but in german the measurement is usually translated and given in "Fuß"

2025-01-03 19:50 UTC, ItsGiantCookie commented
@ZuruZockt010 Yo, any update on my proposed changes?

2025-01-03 20:16 UTC, OverlordZorn commented
> @ZuruZockt010 Yo, any update on my proposed changes?

If you make your proposals as suggestions, they can be directly committed by ether zuru or an kat contributor

2025-01-04 14:46 UTC, ItsGiantCookie commented
> If you make your proposals as suggestions, they can be directly committed by ether zuru or an kat contributor
> 
> 
> 
> https://egghead.io/lessons/github-add-suggestions-in-a-github-pr-review

I always forget that feature, I'll get to it in a bit once I'm home

2025-01-04 15:15 UTC, ItsGiantCookie commented on addons/gui/stringtable.xml
> +            <German>BRUST – KEINE LINIE</German>
```suggestion
            <German>BRUST - KEIN ZUGANG</German>
```

2025-01-04 15:15 UTC, ItsGiantCookie commented on addons/gui/stringtable.xml
> +            <German>RECHTER ARM – KEINE LINIE</German>
```suggestion
            <German>RECHTER ARM – KEIN ZUGANG</German>
```

2025-01-04 15:15 UTC, ItsGiantCookie commented on addons/gui/stringtable.xml
> +            <German>LINKER ARM – KEINE LINIE</German>
```suggestion
            <German>LINKER ARM – KEIN ZUGANG</German>
```

2025-01-04 15:15 UTC, ItsGiantCookie commented on addons/gui/stringtable.xml
> +            <German>RECHTES BEIN – KEINE LINIE</German>
```suggestion
            <German>RECHTES BEIN – KEIN ZUGANG</German>
```

2025-01-04 15:16 UTC, ItsGiantCookie commented on addons/gui/stringtable.xml
> +            <German>LINKES BEIN – KEINE LINIE</German>
```suggestion
            <German>LINKES BEIN – KEIN ZUGANG</German>
```

2025-01-04 15:20 UTC, ItsGiantCookie commented on addons/hypothermia/stringtable.xml
> +            <German>Erlaube Hypothermie</German>
```suggestion
            <German>Hypothermie aktivieren</German>
```

2025-01-04 15:21 UTC, ItsGiantCookie commented on addons/hypothermia/stringtable.xml
> +            <German>Liste der markierten Kleidungsstücke, die den Wärmeverlust reduzieren</German>
```suggestion
            <German>Liste der Kleidungsstücke, die den Wärmeverlust reduzieren</German>
```

2025-01-04 15:29 UTC, ItsGiantCookie commented on addons/hypothermia/stringtable.xml
> +            <German>Hier finden Sie Handwärmer und die geschätzte Zeitdauer in Minuten: %1, %2, %3, %4, %5</German>
Still feels rough but better than before imo
```suggestion
            <German>Hier hast du Handwärmer und wie lange sie deiner Schätzung nach halten werden in Minuten: %1, %2, %3, %4, %5</German>
```

2025-01-04 15:30 UTC, ItsGiantCookie commented on addons/hypothermia/stringtable.xml
> +            <German>prüfe Temperatur</German>
```suggestion
            <German>Prüfe Temperatur</German>
```

2025-01-04 15:31 UTC, ItsGiantCookie commented on addons/hypothermia/stringtable.xml
> +            <German>Überprüfe Handwärmer</German>
```suggestion
            <German>Handwärmer überprüfen</German>
```

2025-01-04 15:46 UTC, ItsGiantCookie commented on addons/stretcher/stringtable.xml
> +            <German>Trage aufräumen</German>
```suggestion
            <German>Trage einpacken...</German>
```

2025-01-04 15:46 UTC, ItsGiantCookie commented on addons/stretcher/stringtable.xml
> +            <German>Trage platzieren</German>
```suggestion
            <German>Trage platzieren...</German>
```

2025-01-04 15:55 UTC, ItsGiantCookie commented on addons/vitals/stringtable.xml
> +            <German>Aktivieren Sie die Patientenflüssigkeitsverschiebung</German>
```suggestion
            <German>Aktiviert Flüssigkeitsverschiebung im Patienten</German>
```

2025-01-04 16:35 UTC, OverlordZorn commented on addons/vitals/stringtable.xml
> +            <German>Wenden Sie vereinfachte Vitalberechnungen auf die KI-Einheit an. Was zum Sparen von FPS nützlich sein kann.</German>
```suggestion
            <German>Vereinfachte Vital-Simulation bei KI-Einheiten. Reduziert Leistungsaufwand.</German>
```

2025-01-04 16:44 UTC, OverlordZorn commented on addons/pharma/stringtable.xml
> +            <German>Koagulation auf AI-Einheiten zulassen.\nAlle anderen Werte sind weiterhin erforderlich, wenn sie aktiviert sind. (Kann zu Verzögerungen führen, wenn viele KI vorhanden sind)</Germ
```suggestion
            <German>Koagulation bei KI-Einheiten simulieren.\nAlle anderen Werte sind weiterhin erforderlich, wenn sie aktiviert sind.\nErhöter Leistungsaufwand bei vielen KI Einheiten.</German>
```

2025-01-05 21:49 UTC, merged