Breathing - Move pneumo hit handling to wounds handler
KAT-Advanced-Medical/KAM pull request #668
Opened 2024-12-19 18:46 UTC by LinkIsGrim

**When merged this pull request will:**
- Title.

I'd also move the tamponade deterioration to a separate function but that's just me.

### IMPORTANT

- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

2025-01-03 21:27 UTC, MiszczuZPolski requested changes

2025-01-03 21:27 UTC, MiszczuZPolski commented on addons/breathing/functions/fnc_woundsHandlerPulmoHit.sqf
> +    _chanceIncrease = linearConversion [GVAR(pneumothoraxDamageThreshold), 3, _damage, 0, 30, true];
missing _damage definition, probably needs to be changed to _engineDamage

2025-01-04 01:54 UTC, LinkIsGrim commented on addons/breathing/functions/fnc_woundsHandlerPulmoHit.sqf
> +    _chanceIncrease = linearConversion [GVAR(pneumothoraxDamageThreshold), 3, _damage, 0, 30, true];
```suggestion
    _chanceIncrease = linearConversion [GVAR(pneumothoraxDamageThreshold), 3, _engineDamage, 0, 30, true];
```

2025-01-04 20:56 UTC, MiszczuZPolski approved these changes

2025-01-04 20:57 UTC, merged