IV fixes and some other stuff
KAT-Advanced-Medical/KAM pull request #87
Opened 2022-04-20 07:39 UTC by mazinskihenry

It'll fix the IVs and should help with some resuscitation issues

2022-04-20 07:43 UTC, MiszczuZPolski commented on addons/pharma/stringtable.xml
> +        <Key ID="STR_ACEP_circulation_IV_DROP_ENABLE">
Shouldn't it be kat instead of ACEP?

2022-04-20 07:44 UTC, mazinskihenry commented on addons/pharma/stringtable.xml
> +        <Key ID="STR_ACEP_circulation_IV_DROP_ENABLE">
AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

2022-04-20 11:12 UTC, YetheSamartaka commented
LGTM.

2022-04-24 19:48 UTC, Tomcat-SG requested changes

2022-04-24 19:48 UTC, Tomcat-SG commented on addons/pharma/stringtable.xml
> +        <Key ID="STR_kat_pharma_IV_DROP_ENABLE">
more languages @MiszczuZPolski xD

2022-04-24 20:28 UTC, Tomcat-SG requested changes

2022-04-24 20:28 UTC, Tomcat-SG commented on addons/pharma/stringtable.xml
> +            <English>Enables IV/IO drop times</English>
```suggestion
            <English>Enables IV/IO drop times</English>
            <German>Aktiviert das herausfallen von IOs/IVs</German>
            <Polish>Włącz wypadanie IV/IO</Polish>
            <Spanish>Habilitar los tiempos de caída de IV/IO</Spanish>
            <Chinese>启用IV/IO下降时间</Chinese>
            <Czech>Povolit čas vypadnutí pro IV/IO</Czech>
            <Korean>IV/IO 드롭 타임 활성화</Korean>
            <French>Activer les délais d'attente pour les IV/IO</French>
            <Turkish>IV/IO bırakma sürelerini etkinleştir</Turkish>
            <Italian>Abilitare i tempi di caduta IV/IO</Italian>
            <Japanese>IV/IOの滴下時間を有効にする</Japanese>
```

2022-04-24 20:28 UTC, Tomcat-SG approved these changes
LGTM

2022-04-24 20:29 UTC, YetheSamartaka commented
LGTM.

2022-04-24 20:29 UTC, merged