Reorientation settings
KAT-Advanced-Medical/KAM pull request #89
Opened 2022-04-20 11:06 UTC by MiszczuZPolski

**When merged this pull request will add:**
- option for enabling/disabling slap sound,
- option for enabling/disabling reorientation,
- option for medical level required for reorientation.

2022-04-20 11:12 UTC, YetheSamartaka commented
LGTM.

2022-04-21 09:34 UTC, MiszczuZPolski commented
Added "Unconscious SpO2 value" to settings

2022-04-24 19:53 UTC, Tomcat-SG requested changes

2022-04-24 19:53 UTC, Tomcat-SG commented on addons/pharma/stringtable.xml
> +            <German>Aktiviert die Umorientieren</German>
```suggestion
            <German>Aktiviert das Umorientieren</German>
```

2022-04-24 19:53 UTC, Tomcat-SG commented on addons/pharma/stringtable.xml
> +            <German>Medizinisches Niveau für Umorientieren erforderlich</German>
```suggestion
            <German>Erforderliches Medic Level zum Umorientieren</German>
```

2022-04-24 19:55 UTC, Tomcat-SG approved these changes
Now LGTM

2022-04-24 20:29 UTC, merged