Translation - Added Russian Translation
KAT-Advanced-Medical/KAM pull request #98
Opened 2022-04-26 16:30 UTC by Nilia119

- Addition of (full) Russian Translation.
- Changed a couple of misspelled "succes" to "success"
- Changed one "Bloodgroups" to "Blood Groups"
- Rephrased STR_kat_misc_Helistretcher_Desc

2022-04-26 16:49 UTC, YetheSamartaka commented
Hello. Nice work. Would you be able to fill in the pharma and zeus translations as well, please?

2022-04-26 16:54 UTC, Nilia119 commented
I can, sadly i fucked up with resolving the conflicts right now. I will report back, once i fixed it.

2022-04-26 18:21 UTC, Nilia119 commented
Done, for me it looks good. I changed Combatt to Combat tho.

2022-04-28 19:30 UTC, Tarveiz commented on addons/airway/stringtable.xml
> +            <Russian>Вероятность закупорки дыхательных путей</Russian>
<Russian>Вероятность обструкции дыхательных путей</Russian>

2022-04-28 19:34 UTC, Tarveiz commented on addons/airway/stringtable.xml
> +            <Russian>Вероятность закупорки дыхательных путей</Russian>
RusTranslate: <Russian>Вероятность окклюзии дыхательных путей</Russian>

2022-04-28 19:45 UTC, Tarveiz commented on addons/airway/stringtable.xml
> +            <Russian>У сообщества под названием Keko был аддон для игроков AFK. Они были лишены сознания, чтобы другие могли их вытащить. Это спровоцировало риск респираторных заболеваний. Эта строка
RusTranslate: <Russian>У сообщества под названием Keko был аддон для игроков в AFK. Они падали без сознания, чтобы другие могли их тащить. Это провоцировало окклюзию и обструкцию дыхательных путей. Эта строка предотвратит это, когда они потеряют сознание из-за этого AFK-аддона.</Russian>

2022-04-28 19:46 UTC, Tarveiz commented on addons/airway/stringtable.xml
> +            <Russian>проверить дыхательные пути</Russian>
RusTranslate: <Russian>Проверить дых. пути</Russian>

2022-04-28 19:48 UTC, Tarveiz commented on addons/airway/stringtable.xml
> +            <Russian>Свернуто</Russian>
RusTranslate: Коллапс

2022-04-28 19:50 UTC, Tarveiz commented on addons/airway/stringtable.xml
> +            <Russian>Всасывание не требуется</Russian>
RusTranslate: Отсос не требуется

2022-04-28 19:54 UTC, Tarveiz commented on addons/airway/stringtable.xml
> +            <Russian>Необходимо управление дыхательными путями</Russian>
RusTranslate: Необходимо проверить дых. пути

2022-04-28 19:57 UTC, Tarveiz commented on addons/airway/stringtable.xml
> +            <Russian>Всасывание необходимо</Russian>
Проверка дых. путей уже была проведена

2022-04-28 20:02 UTC, Tarveiz commented on addons/airway/stringtable.xml
> +            <Russian>Гиперэкстензия головы</Russian>
Фиксация головы

2022-04-28 20:08 UTC, Tarveiz commented on addons/airway/stringtable.xml
> +            <Russian>Повернуть голову в сторону</Russian>
Поворачиваю голову

2022-04-28 20:08 UTC, Tarveiz commented on addons/airway/stringtable.xml
> +            <Russian>Медицинская всасывание не требуется</Russian>
Медицинской отсос не требуется

2022-04-28 20:09 UTC, Tarveiz commented on addons/airway/stringtable.xml
> +            <Russian>Гортанная трубка</Russian>
King LT

2022-04-28 20:12 UTC, Tarveiz commented on addons/airway/stringtable.xml
> +            <Russian>Ларингеальная трубка – это устройство для обеспечения проходимости дыхательных путей.</Russian>
Трубка King LT – это устройство для обеспечения проходимости дыхательных путей.

2022-04-28 20:12 UTC, Tarveiz commented on addons/airway/stringtable.xml
> +            <Russian>Ларингеальная трубка – это устройство для обеспечения проходимости дыхательных путей.</Russian>
Трубка King LT – это устройство для обеспечения проходимости дыхательных путей.

2022-04-28 20:20 UTC, Tarveiz commented on addons/airway/stringtable.xml
> +            <Russian>Когда пациент входит в бессознательное состояние, могут произойти две вещи. В первую очередь могут разрушиться дыхательные пути. В медицинском смысле это означает, что дыхательны
Когда пациент входит в бессознательное состояние, могут произойти две вещи. В первую очередь дыхательные пути могут коллапсировать. В медицинском смысле это означает, что дыхательные пути могут быть заблокированы мышцей языка из-за отсутствия мышечного тонуса. Например, в реальной жизни это произойдет почти с каждым человеком без сознания, лежащим на спине. Второе, что может произойти, так это забитость дыхательных путей различной массой. Когда больной лежит на спине и его рвет, рвота не выходит из ротовой полости. Она останется там и может заблокировать дыхательные пути. Правильное лечение в этом случае - удалить рвоту. В реальной жизни это иногда происходит.

2022-04-28 20:21 UTC, Tarveiz commented on addons/airway/stringtable.xml
> +            <Russian>Вероятность успеха для поворота головы</Russian>
Вероятность успеха очистки при повороте головы

2022-04-28 20:22 UTC, Tarveiz commented on addons/airway/stringtable.xml
> +            <Russian>Разрешить гортанную трубку</Russian>
Разрешить трубку King LT

2022-04-28 20:22 UTC, Tarveiz commented on addons/airway/stringtable.xml
> +            <Russian>Уровень подготовки, необходимый для использования гортанной трубки</Russian>
Уровень подготовки для использования трубки King LT

2022-04-28 20:23 UTC, Tarveiz commented on addons/airway/stringtable.xml
> +            <Russian>Разрешить гедельтубус</Russian>
Разрешить трубку Геделя

2022-04-28 20:24 UTC, Tarveiz commented on addons/airway/stringtable.xml
> +            <Russian>Уровень подготовки, необходимый для использования тубуса Геделя.</Russian>
Уровень подготовки для использования трубки Геделя

2022-05-09 20:59 UTC, Tomcat-SG requested changes

2022-05-09 20:59 UTC, Tomcat-SG commented on addons/circulation/stringtable.xml
> +            <German>Schmerzbekämpfer</German>
```suggestion
            <German>Schmerzmittel</German>
```
```suggestion
            <German>Schmerzbekämpfer</German>
```

2022-05-09 20:59 UTC, Tomcat-SG commented on addons/pharma/stringtable.xml
> +переориентация</Russian>
```suggestion
            <Russian>Включает переориентация</Russian>
```
```suggestion
            <Russian>Включает
переориентация</Russian>
```

2022-05-09 20:59 UTC, Tomcat-SG commented on addons/pharma/stringtable.xml
> +переориентация</Russian>
```suggestion
            <Russian>Включает переориентация</Russian>
```
```suggestion
            <Russian>Включает
переориентация</Russian>
```

2022-05-09 21:02 UTC, Tomcat-SG approved these changes
LGTM

2022-05-09 21:03 UTC, merged