Breathing - Add cyanosis diagnose
KAT-Advanced-Medical/KAM pull request #99
Opened 2022-04-26 16:38 UTC by MiszczuZPolski

**When merged this pull request will:**
- Add cyanosise diagnose with 4 settable levels:
1. No Cyanosis - 100% SpO2
2. Slight Cyanosis - over 90% SpO2 (default)
3. Mild Cyanosis - over 75% SpO2 (default)
4. Severe Cyanosis - over 66% SpO2 (default)

Because some groups doesn't use lethal SpO2 value or have it different from default 65%, all levels are adjustable.

To do:

- Translation for more languages ._.

2022-04-26 19:37 UTC, bababoombatman commented
The level of "no cyanosys" could be modified to be at least over ~95%? Or make it settable? 
I reckon that 100% is good for gameplay perspective, but from a immersion perspective a slight cianosis at 99% would mean that 3/4 of world population is cianotic.

https://journals.lww.com/pec-online/Abstract/2015/09000/Pulse_Oxygen_Saturation_Values_in_a_Healthy.7.aspx
This is a shoold-aged population but the concept is similar

And this without accounting for blood loss that could make cianosis even harder to detect, although i guess that such code would be much more difficult to implement

I don't mean to denigrate it, it's a great idea imo beside this detail!

2022-04-26 19:43 UTC, MiszczuZPolski commented
> The level of "no cyanosys" could be modified to be at least over ~95%? Or make it settable? I reckon that 100% is good for gameplay perspective, but from a immersion perspective a slight cianosis at 99% would mean that 3/4 of world population is cianotic.

I know IRL normal person would have SpO2 lower than 100%, but for gameplay purpose i want to keep it as 100% - that means when someone is injured (for example hidden pneumothorax) medic would know this. 

After commenting this i will add commit for medical level required so Anyone, Medic or Doctor could only detect it based on setting.

2022-05-09 21:43 UTC, Tomcat-SG requested changes
German translation and argument for log changed

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Check Cyanosis</English>
```suggestion
            <English>Check Cyanosis</English>
            <German>Zyanose überprüfen</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Checking Cyanosis</English>
```suggestion
            <English>Checking Cyanosis</English>
            <German>Zyanose prüfen</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/functions/fnc_treatmentAdvanced_CyanosisLocal.sqf
> +[_target, "quick_view", LSTRING(CheckCyanosis_Log), [[_player] call ace_common_fnc_getName, _spO2Output]] call ace_medical_treatment_fnc_addToLog;
```suggestion
[_target, "quick_view", LSTRING(CheckCyanosis_Log), [_spO2Output]] call ace_medical_treatment_fnc_addToLog;
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/functions/fnc_treatmentAdvanced_CyanosisLocal.sqf
> +[_target, "quick_view", LSTRING(CheckCyanosis_Log), [[_player] call ace_common_fnc_getName, _spO2Output]] call ace_medical_treatment_fnc_addToLog;
```suggestion
[_target, "quick_view", LSTRING(CheckCyanosis_Log), [_spO2Output]] call ace_medical_treatment_fnc_addToLog;
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <Polish>Status sinicy: %2</Polish>
```suggestion
            <English>Cyanosis Status: %1</English>
            <German>Status der Zyanose: %1</German>
            <Polish>Status sinicy: %1</Polish>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <Polish>Status sinicy: %2</Polish>
```suggestion
            <English>Cyanosis Status: %1</English>
            <German>Status der Zyanose: %1</German>
            <Polish>Status sinicy: %1</Polish>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>No Cyanosis</English>
```suggestion
            <English>No Cyanosis</English>
            <German>Keine Zyanose</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>No Cyanosis</English>
```suggestion
            <English>No Cyanosis</English>
            <German>Keine Zyanose</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Slight Cyanosis</English>
```suggestion
            <English>Slight Cyanosis</English>
            <German>Leichte Zyanose</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Slight Cyanosis</English>
```suggestion
            <English>Slight Cyanosis</English>
            <German>Leichte Zyanose</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Mild Cyanosis</English>
```suggestion
            <English>Mild Cyanosis</English>
            <German>Mittelschwere Zyanose</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Mild Cyanosis</English>
```suggestion
            <English>Mild Cyanosis</English>
            <German>Mittelschwere Zyanose</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Severe Cyanosis</English>
```suggestion
            <English>Severe Cyanosis</English>
            <German>Schwere Zyanose</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Severe Cyanosis</English>
```suggestion
            <English>Severe Cyanosis</English>
            <German>Schwere Zyanose</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Enable cyanosis diagnose</English>
```suggestion
            <English>Enable cyanosis diagnose</English>
            <German>Zyanose-Diagnose aktivieren</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Enable cyanosis diagnose</English>
```suggestion
            <English>Enable cyanosis diagnose</English>
            <German>Zyanose-Diagnose aktivieren</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Enables cyanosis diagnose</English>
```suggestion
            <English>Enables cyanosis diagnose</English>
            <German>Aktiviert die Zyanose-Diagnose</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Enables cyanosis diagnose</English>
```suggestion
            <English>Enables cyanosis diagnose</English>
            <German>Aktiviert die Zyanose-Diagnose</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Slight cyanosis SpO2 value</English>
```suggestion
            <English>Slight cyanosis SpO2 value</English>
            <German>Leichter Zyanose SpO2-Wert</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Slight cyanosis SpO2 value</English>
```suggestion
            <English>Slight cyanosis SpO2 value</English>
            <German>Leichter Zyanose SpO2-Wert</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Slight cyanosis value - default 90 SpO2</English>
```suggestion
            <English>Slight cyanosis value - default 90 SpO2</English>
            <German>Leichte Zyanose - Standardwert 90 SpO2</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Slight cyanosis value - default 90 SpO2</English>
```suggestion
            <English>Slight cyanosis value - default 90 SpO2</English>
            <German>Leichte Zyanose - Standardwert 90 SpO2</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Mild cyanosis SpO2 value</English>
```suggestion
            <English>Mild cyanosis SpO2 value</English>
            <German>Mittelschwere Zyanose SpO2-Wert</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Mild cyanosis SpO2 value</English>
```suggestion
            <English>Mild cyanosis SpO2 value</English>
            <German>Mittelschwere Zyanose SpO2-Wert</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Mild cyanosis value - default 75 SpO2</English>
```suggestion
            <English>Mild cyanosis value - default 75 SpO2</English>
            <German>Mittelschwere Zyanose - Standardwert 75 SpO2</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Mild cyanosis value - default 75 SpO2</English>
```suggestion
            <English>Mild cyanosis value - default 75 SpO2</English>
            <German>Mittelschwere Zyanose - Standardwert 75 SpO2</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Severe cyanosis SpO2 value</English>
```suggestion
            <English>Severe cyanosis SpO2 value</English>
            <German>Schwere Zyanose SpO2-Wert</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Severe cyanosis SpO2 value</English>
```suggestion
            <English>Severe cyanosis SpO2 value</English>
            <German>Schwere Zyanose SpO2-Wert</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Severe cyanosis value - default 66 SpO2 \nShould be little bit higher than lethal SpO2 value</English>
```suggestion
            <English>Severe cyanosis value - default 66 SpO2 \nShould be little bit higher than lethal SpO2 value</English>
            <German>Schwere Zyanose - Standardwert 66 SpO2 \nSollte etwas höher sein als der tödliche SpO2-Wert</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Severe cyanosis value - default 66 SpO2 \nShould be little bit higher than lethal SpO2 value</English>
```suggestion
            <English>Severe cyanosis value - default 66 SpO2 \nShould be little bit higher than lethal SpO2 value</English>
            <German>Schwere Zyanose - Standardwert 66 SpO2 \nSollte etwas höher sein als der tödliche SpO2-Wert</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Check Cyanosis Minimum Level</English>
```suggestion
            <English>Check Cyanosis Minimum Level</English>
            <German>Zyanose prüfen Medic Level</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>Check Cyanosis Minimum Level</English>
```suggestion
            <English>Check Cyanosis Minimum Level</English>
            <German>Zyanose prüfen Medic Level</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>The minimum medical level required for someone to be able to check cyanosis.</English>
```suggestion
            <English>The minimum medical level required for someone to be able to check cyanosis.</English>
            <German>Das Medic Level, das erforderlich ist, damit jemand eine Zyanose feststellen kann.</German>
```

2022-05-09 21:43 UTC, Tomcat-SG commented on addons/breathing/stringtable.xml
> +            <English>The minimum medical level required for someone to be able to check cyanosis.</English>
```suggestion
            <English>The minimum medical level required for someone to be able to check cyanosis.</English>
            <German>Das Medic Level, das erforderlich ist, damit jemand eine Zyanose feststellen kann.</German>
```

2022-05-09 21:51 UTC, Tomcat-SG approved these changes
LGTM

2022-05-09 21:51 UTC, merged